# Generated by Django 5.0.4 on 2024-05-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0014_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
