# Generated by Django 5.0.4 on 2024-05-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0015_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discord_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
